// Code generated by taoctl. DO NOT EDIT!
// Source: article.proto

package server

import (
	"context"

	"sllt/backend-learning/blog/rpc/article/article"
	"sllt/backend-learning/blog/rpc/article/internal/logic"
	"sllt/backend-learning/blog/rpc/article/internal/svc"
)

type ArticleServer struct {
	svcCtx *svc.ServiceContext
}

func NewArticleServer(svcCtx *svc.ServiceContext) *ArticleServer {
	return &ArticleServer{
		svcCtx: svcCtx,
	}
}

//  获取全部文章
func (s *ArticleServer) GetAllArticle(ctx context.Context, in *article.GetAllArticleReq) (*article.GetAllArticleResp, error) {
	l := logic.NewGetAllArticleLogic(ctx, s.svcCtx)
	return l.GetAllArticle(in)
}

//  获取文章详情
func (s *ArticleServer) GetArticle(ctx context.Context, in *article.GetArticleReq) (*article.GetArticleResp, error) {
	l := logic.NewGetArticleLogic(ctx, s.svcCtx)
	return l.GetArticle(in)
}

//  创建文章
func (s *ArticleServer) CreateArticle(ctx context.Context, in *article.CreateArticleReq) (*article.CreateArticleResp, error) {
	l := logic.NewCreateArticleLogic(ctx, s.svcCtx)
	return l.CreateArticle(in)
}
