// Code generated by taoctl. DO NOT EDIT.
package handler

import (
	"net/http"

	article "sllt/backend-learning/blog/api/internal/handler/article"
	reply "sllt/backend-learning/blog/api/internal/handler/reply"
	"sllt/backend-learning/blog/api/internal/svc"

	"manlu.org/tao/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/posts",
				Handler: article.PostsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/post/:id",
				Handler: article.PostDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/create",
				Handler: article.CreatePostHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/post/:id/reply",
				Handler: reply.CreateReplyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/post/:id/replies",
				Handler: reply.GetReplyHandler(serverCtx),
			},
		},
	)
}
